# Generated by Django 4.1.3 on 2022-12-05 21:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('Week1', 'Week1'), ('Week2', 'Week2'), ('Week3', 'Week3'), ('Week4', 'Week4'), ('Week5', 'Week5'), ('Week6', 'Week6'), ('Week7', 'Week7'), ('Week8', 'Week8'), ('Week9', 'Week9'), ('Week10', 'Week10'), ('Week11', 'Week11'), ('Week12', 'Week12'), ('Week13', 'Week13'), ('Week14', 'Week14'), ('Week15', 'Week15'), ('Week16', 'Week16'), ('Week17', 'Week17'), ('Week18', 'Week18'), ('Week19', 'Week19'), ('Week20', 'Week20'), ('Week21', 'Week21'), ('Week22', 'Week22'), ('Week23', 'Week23'), ('Week24', 'Week24'), ('Week25', 'Week25'), ('Week26', 'Week26'), ('Week27', 'Week27'), ('Week28', 'Week28'), ('Week29', 'Week29'), ('Week30', 'Week30')], max_length=200)),
                ('day', models.CharField(choices=[('Day1', 'Day1'), ('Day2', 'Day2'), ('Day3', 'Day3'), ('Day4', 'Day4'), ('Day5', 'Day5'), ('Day6', 'Day6'), ('Day7', 'Day7')], max_length=200)),
                ('moment', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=200)),
                ('name_course', models.CharField(max_length=200)),
                ('type_course', models.CharField(choices=[('Course', 'Course'), ('TA', 'TA'), ('Checker', 'Checker'), ('Support', 'Support')], max_length=200)),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('contract', models.CharField(choices=[('Employee', 'Employee'), ('Freelancer', 'Freelancer')], max_length=200)),
                ('devise', models.CharField(choices=[('ILS', 'ILS'), ('EUR', 'EUR'), ('MUR', 'MUR'), ('CFA', 'CFA'), ('USD', 'USD')], max_length=200)),
                ('rate_course', models.IntegerField(default=0)),
                ('rate_ta', models.IntegerField(default=0)),
                ('rate_checker', models.IntegerField(default=0)),
                ('rate_support', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('course_done', models.BooleanField(default=True)),
                ('hours', models.IntegerField(blank=True, default=0)),
                ('moment', models.CharField(default='Morning', max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('week', models.CharField(blank=True, max_length=200)),
                ('week_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)])),
                ('day', models.CharField(blank=True, max_length=200)),
                ('coursefulltime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.course')),
                ('instructor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructorfulltime', to='App.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_structure', models.CharField(max_length=200)),
                ('courses', models.ManyToManyField(blank=True, null=True, related_name='structures', to='App.course')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('instructors', models.ManyToManyField(blank=True, related_name='programs', through='App.InstructorProgram', to='App.instructor')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.structure')),
            ],
        ),
        migrations.AddField(
            model_name='instructorprogram',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.program'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', through='App.InstructorProgram', to='App.instructor'),
        ),
    ]
