# Generated by Django 4.1.3 on 2022-12-08 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_coursefulltime_instructorprogram_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_date', models.DateField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.course')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.program')),
            ],
        ),
    ]
