# Generated by Django 4.1.3 on 2022-12-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_programdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdate',
            name='new_day',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programdate',
            name='new_week',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
