# Generated by Django 4.1.3 on 2022-12-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_programdate_new_day_programdate_new_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
