# Generated by Django 4.1.3 on 2022-12-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_program_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='course_access',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='email_program',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='google_meet_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='link_attendance',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='public_calendar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='slack_room',
            field=models.URLField(blank=True),
        ),
    ]
