# Generated by Django 4.1.3 on 2022-12-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_program_course_access_program_email_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('added_date', models.DateField(auto_now_add=True)),
                ('files', models.FileField(max_length=254, upload_to=None)),
                ('budget', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('Waiting', 'Waiting'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Complete', 'Complete')], max_length=50)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.program')),
                ('team', models.ManyToManyField(blank=True, related_name='tasks', to='App.instructor')),
            ],
        ),
    ]
