# Generated by Django 4.1.3 on 2022-12-12 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='budget',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.FileField(blank=True, max_length=254, upload_to=None),
        ),
    ]
