# Generated by Django 4.1.3 on 2022-12-15 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_task_budget_alter_task_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='App.program'),
        ),
    ]
